
development:
  adapter: sqlite3
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: my_database_test
  pool: 5
  timeout: 5000
  
production:
  host: course-database.cbacagteikko.us-east-1.rds.amazonaws.com
  database: course-database
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: postgres
  password: SVpswAx7VJGMtU6jhpSJ